services:
  app:
    image: lorenzocattaneo/laravel:8.4-dev
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    # environment:
    #   can be "fpm", "octane-frankenphp", "octane-swoole" or "octane-rr"
    #   - SERVER_TYPE=octane-frankenphp

  # queue:
  #   image: lorenzocattaneo/laravel:8.4-dev
  #   command: php artisan queue:listen
  #   volumes:
  #     - .:/var/www/html
  #   depends_on:
  #     - app
  #     - db

  # schedule:
  #   image: lorenzocattaneo/laravel:8.4-dev
  #   command: php artisan schedule:work
  #   volumes:
  #     - .:/var/www/html
  #   depends_on:
  #     - app
  #     - db

  db:
    image: mariadb:11.8
    ports:
      - "3336:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MARIADB_DATABASE: db_test
      MARIADB_ROOT_PASSWORD: password

  # db:
  #   image: pgvector/pgvector:pg17
  #   restart: always
  #   volumes:
  #     - ./dbdata:/var/lib/postgresql/data
  #   user: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "5433:5432"
  #   healthcheck:
  #     test: [ "CMD", "pg_isready" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - "6379:6379"

networks:
  default:
    driver: bridge
