version: '3.9'

services:
  app:
    image: lorenzocattaneo/laravel:8.2-dev
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  queue:
    image: lorenzocattaneo/laravel:8.2-dev
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
      - app
    command: php artisan queue:work

  schedule:
    image: lorenzocattaneo/laravel:8.2-dev
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
      - app
    command: php artisan schedule:work

  db:
    image: mariadb:11.1-rc
    ports:
      - "3336:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network
    environment:
      MARIADB_DATABASE: db_test
      MARIADB_ROOT_PASSWORD: password

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  soketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    ports:
      - "6001:6001"
      - "9601:9601"
    networks:
      - app-network
    environment:
      - SOKETI_DEBUG=1

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
