name: Build Docker Images

on:
  push:
    branches:
      - 'main'

# permissions are needed if pushing to ghcr.io
permissions: 
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./8.2/Dockerfile
          tags: lorenzocattaneo/laravel:8.2
          platforms: linux/arm64,linux/amd64
          push: true
          provenance: false
          
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./8.2/dev/Dockerfile
          tags: lorenzocattaneo/laravel:8.2-dev
          platforms: linux/arm64,linux/amd64
          push: true
          provenance: false

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./8.3/Dockerfile
          tags: lorenzocattaneo/laravel:8.3
          platforms: linux/arm64,linux/amd64
          push: true
          provenance: false
          
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./8.3/dev/Dockerfile
          tags: lorenzocattaneo/laravel:8.3-dev
          platforms: linux/arm64,linux/amd64
          push: true
          provenance: false